### ISSUE TITLE
Using a different attribute prefix

### ISSUE THREAD

**Issue by bentesha** [OmarShehe/FormInputs#1]
Hello @OmarShehe 

Thanks for a lot of work you have put into this project.

I wanted to hear your opinion on using a different attribute prefix. Instead of **customer** I thought using something more general would have been a good improvement.

What do you think of using **custom,** **form**, or **fi** (for form inputs) instead of customer for attribute prefix?

**Comment by OmarShehe** [comment]
Hello @bentesha 

Thank you for taking the time to create an issue.
It's a good idea,  I will use **form** instead. I will add it in the next commit.

**Comment by bentesha** [comment]
@OmarShehe 
Yes, **form** should be awesome!

On the side note, I noticed you are in Zanzibar, I am based in Dar es salaam!
Will mail you soon!

**Comment by OmarShehe** [comment]
@bentesha 
Cool
