### ISSUE TITLE
Currency input

### ISSUE THREAD

**Issue by jilenloa** [OmarShehe/FormInputs#2]
I cannot able to accept decimal when using number input type

**Comment by OmarShehe** [comment]
Hi @jilenloa, I already update it. Use this snapshot for now `com.github.OmarShehe.FormInputs:forminputkotlin:-SNAPSHOT`

**Comment by jilenloa** [comment]
> Hi @jilenloa, I already update it. Use this snapshot for now `com.github.OmarShehe.FormInputs:forminputkotlin:-SNAPSHOT`

Thanks for your swift response
