### ISSUE TITLE
What LICENSE ?

### ISSUE THREAD

**Issue by dentex** [OmarShehe/FormInputs#3]
Thanks for this nice library. 
Do you mind to add a license file to it? I would like to include this lib in a product (... if I'll ever finish it).

Thanks.

**Comment by OmarShehe** [comment]
@dentex 
It's an open source project and I will add the licence file to it.

**Comment by dentex** [comment]
Great, thanks!

**Comment by dentex** [comment]
Would you consider a less strict license as the MIT or Apache licenses?

Thanks

**Comment by OmarShehe** [comment]
Okay, I will use MIT license.

**Comment by dentex** [comment]
I LOVE you man...
Thanks.
