### ISSUE TITLE
Styling the inputs

### ISSUE THREAD

**Issue by cherimo** [OmarShehe/FormInputs#6]
Hi there,

Thank you for the library.
Is there any documentation or information about styling the inputs?
I am using a custom dark theme and the colors don't match up at the moment.

I can change the background color of the input with:
`app:customer_background="@drawable/radius_input_2"`
But how can I change the input text color to white?
It still always black no matter what I change in the XML attribute.

Thank you in advance.

**Comment by OmarShehe** [comment]
Hi @cherimo 

For now, there is no proper documentation, but you can check the app folder. There are examples of how to use the library.
I just update the library to this version 'com.github.OmarShehe.FormInputs:forminputkotlin:1.0.4'
The color changes now are working. Check the app folder for examples.

**Comment by cherimo** [comment]
@OmarShehe  Thank you for your fast response and for the update everything works fine now 👍
