### ISSUE TITLE
FormInputAutoComplete on item selected

### ISSUE THREAD

**Issue by rizkikurniaa** [OmarShehe/FormInputs#8]
Hi, i made an array of province that has id and province_name. How can i got the id if i select the province? there is no example i find in this project. For now only province name that shown on my apps, i need the id too. Thank you

**Comment by OmarShehe** [comment]
Hi @rizkikurniaa, Thank you for taking the time to create an issue. I will look into your question and get back to you soon.

**Comment by OmarShehe** [comment]
Hi, @rizkikurniaa again. Unfortunately, the `FormInputAutoComplete` currently only supports a list of strings, so there is no way to pass the ID in the list.
In the meantime, you can use this workaround

Let's say you have a data class like this
`data class ProvinceModel(val id: Int, val name: String)`
and with a list like this
```
val provinceList = listOf(
      ProvinceModel(1, "province 1"), ProvinceModel(2, "province 2")
)
```
You could do this

 ```
val provinceNameList = provinceList.map { it.name } // convert into string list of names

 autoCompleteView.setAdapter(provinceNameList)
 autoCompleteView.setOnItemSelectedListener(object : ItemSelectedListener {
        override fun onItemSelected(item: String) {
             val provinceId = provinceList.find { it.name == item }?.id // find the province item by name
         }
 })
```

I hope this helps you solve your issue.

**Comment by rizkikurniaa** [comment]
thank you! you saved my day! :D

**Comment by rizkikurniaa** [comment]
thank you! you saved my day! :D
